# Для продакшена (без сборки, только образы из реестра)
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: prac
      POSTGRES_USER: prac
      POSTGRES_PASSWORD: prac
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: ghcr.io/xwarrainx/film-backend:latest
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: prac
      DATABASE_PASSWORD: prac
      DATABASE_NAME: prac
    depends_on:
      - postgres

  nginx:
    image: ghcr.io/xwarrainx/film-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - frontend-dist:/usr/share/nginx/html:ro

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  postgres_data:
  frontend-dist: